### ISSUE TITLE
On Activation Checkif WPML installed

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodir-multilingual#11]
On Activation - fail to activate if WPML is not installed

Notification should say:

GeoDirectory Multilingual Requires
  - sitepress-multilingual-cms
  - wpml-translation-management
  - wpml-string-translation
  - wpml-media-translation
  - wpml-sticky-links

**Comment by kprajapatii** [comment]
Fixed via https://github.com/AyeCode/geodir-multilingual/pull/14/commits/b59b1b45be1991272eba1696e2ba651e9145e1ab

It will not load GeoDirectory WPML file/class/functions if WPML plugin not active.
