### ISSUE TITLE
Multisite issue?

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodir-multilingual#40]
![Screenshot from 2021-01-26 17-37-04](https://user-images.githubusercontent.com/10433311/105882107-3118b700-5ffd-11eb-830b-0b1f58f88ea8.png)

**Comment by kprajapatii** [comment]
I checked on my test site and did not replicate. do you have site details to look more there?

Right now it uses wp_icl_t as a prefix, but here in query it shows icl_t, so might it is added by old snippet or version.
